-- begin PLANNER_SPEAKER
create unique index IDX_PLANNER_SPEAKER_UNIQ_EMAIL on PLANNER_SPEAKER (EMAIL)^
create index IDX_PLANNER_SPEAKER_LAST_NAME on PLANNER_SPEAKER (LAST_NAME)^
-- end PLANNER_SPEAKER
-- begin PLANNER_SESSION
alter table PLANNER_SESSION add constraint FK_PLANNER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNER_SPEAKER(ID)^
create index IDX_PLANNER_SESSION_ON_SPEAKER on PLANNER_SESSION (SPEAKER_ID)^
-- end PLANNER_SESSION
