alter table PLANNER_SESSION add constraint FK_PLANNER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references PLANNER_SPEAKER(ID);
create index IDX_PLANNER_SESSION_ON_SPEAKER on PLANNER_SESSION (SPEAKER_ID);
